### ISSUE TITLE
Can this be used to control the external unit without indoor unit?

### ISSUE THREAD

**Issue by tomekit** [marekorok/modbus-midea#2]
Hi @marekorok,

I was wondering if this can be used to talk directly to external unit, skipping the internal unit?

Looking to convert Rotenso to heat pump and would get only the external unit.

Thanks!

**Comment by marekorok** [comment]
Hi Tomek,

sorry for late reply.

Very likely it will not work
The internal unit communicates with external over proprieraty Midea protocol and the XYE connectors, and here we are using AB connect, standard modbus over RS485.

Disclaimer I might be totally wrong and somebody already implemented it, but I  never seen it.

You can check these threads:
https://community.home-assistant.io/t/midea-branded-ac-s-with-esphome-no-cloud/265236/711?page=36
https://renewableheatinghub.co.uk/forums/renewable-heating-air-source-heap-pumps-ashps/real-world-connection-to-a-heat-pump-over-modbus/paged/3

Cheers
