### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by BadMud** [marekorok/modbus-midea#3]
Cześć,

Mam pytanie jakich części używasz, możesz podesłać jakieś zdjęcia, dobrze kojaże że jest to wemos plus "coś" ?

Pozdrawiam
Bartek

**Comment by marekorok** [comment]
Hej, tak ten projekt zbudowałem na najtańszym ESP12 plus RS485 XY
![image](https://github.com/user-attachments/assets/e2176143-ddda-4877-b0bf-5045c24e243a)

Dzisiaj bym użył Atom S3 z RS485, o wiele ładniejsze rozwiązanie:
![image](https://github.com/user-attachments/assets/30696215-ecec-495c-9d35-ef8a0fb4bda7)

Ale ciągle działa więc nic nie ruszam :-)

Pozdrawiam, Marek

**Comment by BadMud** [comment]
Dziękuje, za błyskawiczną odpowiedź, Będe próbował podpiąć pompę York (piszą że to clon) z serii YKF07CNC.
Pozdrawiam

**Comment by marekorok** [comment]
ok, pozaglądaj tutaj:
https://renewableheatinghub.co.uk/forums/renewable-heating-air-source-heap-pumps-ashps/real-world-connection-to-a-heat-pump-over-modbus/paged/3
https://community.home-assistant.io/t/midea-branded-ac-s-with-esphome-no-cloud

Dużo wiedzy z której sam korzystałem.

Pozdrawiam,
